### ISSUE TITLE
order complete, order cancelled is on the original language

### ISSUE THREAD

**Issue by vonsch76** [qTranslate-Team/woocommerce-qtranslate-x#12]
John, Michael, 

Noticed that you modified the plugin to keep the original language through the order process. To be honest, I already noticed the problem (including the issue that the admin language is always the email language), but managed to solve that in functions.php quick and easy.

```
add_filter('woocommerce_new_customer_note', 'hajoznijo_customer_note_language_fix', 1, 2);
add_filter('woocommerce_order_status_completed', 'hajoznijo_order_complete_language_fix', 1);
add_filter('woocommerce_order_status_cancelled', 'hajoznijo_order_complete_language_fix', 1);

function hajoznijo_customer_note_language_fix ( $args ) {
        $defaults = array(
        'order_id' => '',
        'customer_note' => ''
        );
        $args = wp_parse_args( $args, $defaults );
        extract( $args );
        hajoznijo_language_fix( $order_id);
        return ($args);
}
function hajoznijo_language_fix( $order_id ){
    $new_locale = get_post_meta( $order_id, 'language', true);
    unload_textdomain('woocommerce');
    setlocale(LC_ALL, $new_locale);
    global $q_config, $woocommerce;
    $q_config['language'] = substr($new_locale, 0, 2);
    $woocommerce->load_plugin_textdomain();
    return;
}
function hajoznijo_order_complete_language_fix( $order_id ){
    hajoznijo_language_fix ( $order_id );
    return $order_id;
} 
```

True, correcting from the plugin is the neat solution. Please add the order_status_competed and order_status_cancelled scenario, as the user tend to receive email on that as well.

Thanks,
Kornel

**Comment by johnclause** [comment]
Does it solve the problem left unsolved here: https://github.com/qTranslate-Team/woocommerce-qtranslate-x/issues/3

**Comment by vonsch76** [comment]
If you implement, then it should. This code works on my page for a while.
If somebody is sending mails on other woocommerce events, then we also need
to address those as well. This only addresses order completed and order
cancelled. The original order you don't need to touch as that goes on the
order language.

**Comment by vonsch76** [comment]
There is one - known - disadvantage, though. If anything is saved in
woocommerce settings - other than the English default text - then
translation will not work!

**Comment by johnclause** [comment]
I assume this is ok now can be closed? We can still write to closed issue and ca re-open it if necessary.

**Comment by vonsch76** [comment]
John,
The problem is still there, Michael only solved customer note, the rest
still goes in system language. I would rather call that buggy than solved.
Tried to contact with Michael direct, no reply.
Kornel

**Comment by johnclause** [comment]
Hi Kornel, I see some solution code and critics, but I do not see a description of the problem you are solving. Can you give us the steps to reproduce the problem which needs to be solved?

**Comment by vonsch76** [comment]
John,

The problem short: WC order related mails are sent on system (admin)
language.

So, if you have a site in EN, FR, DE, etc. you get an order in German, then
the first email (order confirmation) is fine (German) the second and
additional emails (like customer note, order closed, etc.) are sent on
system language (whatever is set - assume English).

The solution is to store user (order) language and use that for each mail.
This is what Michael did and use for customer note. Unfortunately there are
other mails like the ones I noted which goes in system language.

The working fix is to reload WC with the order language.

Kornel

**Comment by johnclause** [comment]
Last time I tested, service e-mails were going in the original language of order. I need exact steps to reproduce, what I click, on which page, as you and I apparently testing different things.

**Comment by vonsch76** [comment]
Will check and get back to you. Maybe it is only my setup.

**Comment by vonsch76** [comment]
Jonh,

Sorry, you were right. The template files in theme/woocommerce tricked me.
Actually the version number was identical, but the content was already
different. (WC 2.2 and WC 2.3 templates are different even if the version
number does not say that.)

You can cancel this.

Thanks,
Kornel

**Comment by johnclause** [comment]
I am very glad you are fine now, Kornel!
