### ISSUE TITLE
New coupons are not recognized

### ISSUE THREAD

**Issue by Haxtro** [qTranslate-Team/woocommerce-qtranslate-x#13]
Good morning,

There seems to be an odd issue, coupons created before using qTranslate X seems to work perfectly fine. However, when adding new coupons, they won't get recognized. I've been looking over the web and did not find a similar issue.

Thanks.

Haxtro

**Comment by johnclause** [comment]
Hi @Haxtro: we need steps to reproduce the problem without assuming any knowledge of Woocommerce.

Other questions: Do you think coupons should be multilingual? The latest version of QTX from [GitHub](https://github.com/qTranslate-Team/qtranslate-x/archive/master.zip) allows to disable translation for specific post types. You may try to exclude type 'shop_coupon'.

Maybe 'Coupon code' field must not be multilingual? Try putting exactly the same value for each language (which causes to remove language tags) and see if problem stays.

Please, describe the way coupons would work for you in terms of multilingual features. Like, which fields needs to be multilingual if any?

**Comment by Haxtro** [comment]
Hi @johnclause, thanks for your response.

The problem is quite easy to reproduce. Everything works fine when qTranslate X is disabled. However, when it's activated, previously created coupons are still working fine. New created coupons will give the error that they don't exist when added in shopping cart. I've tried to edit a previously working coupon to a new name, saved it and gave the error again.

I think coupons should not be multilingual, since most of the time they are names or random characters. This indeed seems to cause the problem. I tried all combinations with the languages ( Dutch & English ), both same coupon name, one language only etc.. The [:en] etc seem to cause it. 

In my opinion there is no need to translate coupons in the backend. As far as I know there is no possibility for the customer to see the description of the coupon, so it would only be helpful for the administrator. 

I tried the latest version of QTX, but I somehow fail to find the option of disabling translation fields. I just see the options to add filters and fields.

Thanks a lot!

**Comment by johnclause** [comment]
There is one place only where all the options of QTX are listed: `/wp-admin/options-general.php?page=qtranslate-x`. Look for row "Post Types". If coupons need not to be multilingual, then, I believe, disabling post type 'shop_coupon' should solve the problem.

When I tried to add new coupon, I saw field "Coupon Description", which is currently not multilingual, but it seems that this would be the only field which might be multilingual for coupons. Do you know how it is used? Do you fill it in your case?

**Comment by Haxtro** [comment]
Thanks again for the response. I missed the row Post Types indeed, due to the use of the Dutch settings. Turned English on and it was easier to find. Indeed, this seems to fix the problem!

I never fill in the Coupon Description, but I could think of cases where it might come handy. For example when using randomized coupon codes, you could fill in the name of the person to whom you handed the coupon. Now with shop_coupon disabled, the coupon itself doesn't get translated anymore and won't cause problems in the checkout. That's great!

Thanks a lot! Let me know if you need any other feedback, else feel free to close the issue.

**Comment by vonsch76** [comment]
Actually the issue is caused by the fact that the coupon exists on one language, but the title is not duplicated on the other language(s). As a result, the coupon might not be available. If the title is copied, then it is fine. Had the same and from that time put effort to check. Will try "Post Types" solution as well.

**Comment by vonsch76** [comment]
Is 'Post Types' new? Have only Ignore Links and Custom Fields.

**Comment by johnclause** [comment]
Yes, "Post Types" is new, here is the quote from the above:

> The latest version of QTX from [GitHub](https://github.com/qTranslate-Team/qtranslate-x/archive/master.zip) allows to disable translation for specific post types.

Other quote:

> Try putting exactly the same value for each language (which causes to remove language tags) and see if problem stays.

I read that the coupon code need not to be multilingual, kind of obvious, but they use the "title" field, which automatically gets to be translatable. This page does not have any alteration through the integration plugin.

Do you  think description field needs to be translatable? We may adjust the configuration in the future release of integration plugin "Woocommerce & qTranslate-X".

**Comment by vonsch76** [comment]
No, John, no field of the coupon needs to be translated. It is all
internal, WooCommerce uses the title to identify, the content of the coupon
is for the shop owner, the user sees nothing from it.

Here is how you create a coupon from the code

http://docs.woothemes.com/document/create-a-coupon-programatically/

As you can see only the coupon code (name), discount type and amount are
the important fields.

The problem can be eliminated even with the current version by a simple
copy and paste of the title.

Kornel

**Comment by johnclause** [comment]
Good, then we simply need to disable  'shop_coupon' in 'Post Types'.

> The problem can be eliminated even with the current version by a simple
> copy and paste of the title.

Correct.
