### ISSUE TITLE
Product Variation not working 

### ISSUE THREAD

**Issue by Nexty-Pty-Ltd** [qTranslate-Team/woocommerce-qtranslate-x#15]
Hi, I using WooCommerce & qTranslate-X in my theme, but I found that "Product Data" not changing when I switch language tabs.

Could you have a look at this problem? BTW, I am using WooCommerce & qTranslate-X 1.1 and qTranslate-X 3.3 version, also WooCommerce 2.3.8.

Thanks

**Comment by johnclause** [comment]
Which field in "Product Data" do you wish to be multilingual?

**Comment by Nexty-Pty-Ltd** [comment]
i have attached a screenshot of my dashboard.  The whole "Product Data" not switched while switch the language tabs.

Thanks
![snip20150518_2](https://cloud.githubusercontent.com/assets/5996085/7673223/3f50e14e-fd52-11e4-85b1-44dff4314cb1.png)

**Comment by johnclause** [comment]
It does for me. Can you provide the steps to reproduce a problem? Please, use the latest qTranslate-X from GitHub version https://github.com/qTranslate-Team/qtranslate-x, so that we would not do the work twice.

**Comment by Nexty-Pty-Ltd** [comment]
I tried the latest qtranslate-x from GitHub version, it is not working either. Even the language switch tab is gone.   What do you mean by the steps to reproduce problem?  

![snip20150518_3](https://cloud.githubusercontent.com/assets/5996085/7673464/4ad505d6-fd57-11e4-909f-dd039740aed8.png)

**Comment by Nexty-Pty-Ltd** [comment]
I installed the qTranslate X 3.3 version firstly, It is working fine in most part of my theme, only the "Product  Data" of Woocommerce is not working. Then I tried qTranslate X & Woocommerce to enable multilingual in that part. It is still not working when I switch the language tab.

Sorry for the duplicate issue posted on your website.

Thanks

**Comment by Nexty-Pty-Ltd** [comment]
Any one have this problem ?

Thanks

**Comment by johnclause** [comment]
> Even the language switch tab is gone

Could you look up an error in "Javascript console" (Crtl+Shift+J)? It must be something on your theme or a conflicting plugin.

No, I did not hear from anyone else on this problem. Which fields exactly in "Product Data" do you miss to be multilingual?

**Comment by ginsterbusch** [comment]
To chime in here: Disable any BROWSER extensions that might interfere, eg. any kind of Adblock (ABP is one of these). If you're using Firefox, use the Firebug extension to identify JS errors more easily. The JS console in both Chrome and FF is pretty plain compared with the full-blown "torch" of Firebug.

cu, w0lf.

**Comment by Nexty-Pty-Ltd** [comment]
@johnclause  The "Attributes" is what i want to be multilingual.  Actually the whole options under Product Data is not available to be switched. I guess the latest version of woocommerce-qtranslate-x can not work properly on wordpress 4.0.3.  

BTW, I used the latest version of ACF qTranslate with ACF plugin, custom field can not be switched either; but after I switched to 1.7.7 of ACF qTranslate, it is working !  

Thanks

**Comment by johnclause** [comment]
If there are issues with ACF qTranslate report them to the authors.

Is this now resolved when the latest WP is used?

**Comment by Kjalle** [comment]
@johnclause no I have the exact same problem. 

Tried a clean install of latest wordpress, latest q translate x and latest woocommerce. Them I'm using is twentyfifteen from wordpress.

None of the product data fields can be switched/translated :(

If you need any more info let my know, I would really like to solve this problem.

**Comment by johnclause** [comment]
Hi All, Could you try both latest versions https://github.com/qTranslate-Team/woocommerce-qtranslate-x and see if problem is gone? Read section "[Known Issues](https://github.com/qTranslate-Team/woocommerce-qtranslate-x#known-issues)"  in order not to report what is already known.

**Comment by johnclause** [comment]
I am closing this issue for now, as it should be resolved is the latest releases. We can still write into a closed issue, or we can re-open it, if needed.
