### ISSUE TITLE
Slug

### ISSUE THREAD

**Issue by Filoz** [qTranslate-Team/woocommerce-qtranslate-x#16]
hello, thanks for your work !.
I could not understand only one thing:
The slug of categories and products can be translated?
Or the slug is the same for all languages?

thanks a lot!

**Comment by johnclause** [comment]
Slug is the same for all languages. Plugin [QTranslate Slug](https://wordpress.org/plugins/qtranslate-slug/) helps to translate the slugs, but it is [currently broken](https://github.com/not-only-code/qtranslate-slug/issues/108) with the latest beta version of qTranslate-X. People reported that it was more or less ok with qtx version 3.3. We may implement slug translation natively under qTranslate-X in a couple of releases.

I am closing this issue for now, we can still write into a closed issue, or we can re-open it, if needed.

**Comment by ginsterbusch** [comment]
so .. to get that additional plugin working, one simply would have to fork and fix it, right? ;)

cu, w0lf.

**Comment by johnclause** [comment]
Right. Same for implementing it under qtx natively. Ant btw, same with everything, which is not working ;)

BTW, if you are using 3.3, you may try qts and let us know if it works with Woocommerce?

**Comment by ginsterbusch** [comment]
@johnclause yep, will do. got a project with that right at hand ;)

cu, w0lf.
