### ISSUE TITLE
Woocommerce attributes are not saved after product update

### ISSUE THREAD

**Issue by lluuccaass** [qTranslate-Team/woocommerce-qtranslate-x#29]
Hi,

i am using:
WooCommerce – Version 2.5.5 
WooCommerce & qTranslate-X – Version 1.3.1
qTranslate-X – Version 3.4.6.7

It's a fresh installation.

After setting up custom product attributes (also normal product attributes), saving them and publishing the product they disappear.
Without qTranslate-X activated everything is working normally.

I found a lot about not translated attributes, but no information about not shown attribues at all.

Thanks for your help!

**Comment by johnclause** [comment]
Does reply at [WP](https://wordpress.org/support/topic/woocommerce-attributes-are-not-saved-after-product-update) help?

**Comment by lluuccaass** [comment]
thanks for your reply. i already saw it and tried to fix it. but it's not working for me.

the strange thing is, when i save the custom product attributes in the tab menu, its saved and visible at the front end. just after updating / publishing the product it's gone

**Comment by johnclause** [comment]
I am not sure if it would help, but you may try the latest qtx soon to be released: https://github.com/qTranslate-Team/qtranslate-x/archive/stable.zip too.

BTW, which language is active when you update the product, the default one or other one? Try to do it under the default language, does this change anything?

**Comment by lluuccaass** [comment]
Thanks. I tried the lastest version you posted to me.  What a bummer, it's still disappearing.

English is my default language. No changes, i also tried to disable the second language. As long qtranslate is active, the issue still exists.

Could a Woocommerce / qTranslate downgrade solve the problem?

**Comment by johnclause** [comment]
No, I do doubt downgrading will help. Well, at this point, we need to be
able to reproduce what you see, and so far I could not. Maybe we should
make use one of the ways for admin access: https://qtranslatexteam.wordpress.com/admin-access/ ?

**Comment by lluuccaass** [comment]
hi,

i found the problem. strangely enough it was not directly connected to qTranslate. it was probalby a advanced custom field which caused the problems or a php variable  which i used for ACF which i named $product_attribute (maybe this was doubled somewhere?). i dont know. so please close this issue, thanks a lot

**Comment by johnclause** [comment]
Great! I can only wish all issues would close this way :+1:
