### ISSUE TITLE
Bad meta on certain types of Woocommerce pages (eg category)

### ISSUE THREAD

**Issue by sailinf** [qTranslate-Team/woocommerce-qtranslate-x#31]
There seem to be some problems with meta in a number of case on my site that might be related to qTranslate. Here is an illustration of the problem excerpt:

`<link hreflang="en" href="https://site.fi/en/product-category/helsinki/" rel="alternate" />
<link hreflang="fi_FI" href="https://site.fi/fi/product-category/helsinki/" rel="alternate" />
<link hreflang="x-default" href="https://site.fi/product-category/helsinki/" rel="alternate" />
<meta name="generator" content="qTranslate-X 3.4.6.8" />
<meta property="og:site_name" content="Site"><meta property="og:title" content="Meeting at sea, Helsinki-Espoo"><meta property="og:description" content="Best boating in Finland"><meta property="og:image" content="https://site.fi/wp-content/uploads/2016/03/SKUM-4.jpg"><meta property="og:url" content="https://site.fi/en/kauppa/meeting-at-sea/"><meta property="og:type" content="website">
`

Problem/question: inconsistent use of reflang ("en" vs "fi_FI"), not sure if this matters?

Question: is the meta below the ' content="qTranslate-X 3.4.6.8" ' tag generated by qTranslate?

The problem is that this is not the meta for the page (a WooCommerce category page) but instead for the first product that appears on the page. This is a problem because this meta blocks the correct meta included later on the page, the correct meta would be:
`
<meta property="og:site_name" content="site"/>
<meta property="og:title" content="Boat charter Helsinki"/>
<meta property="og:url" content="https://site.fi/en/product-category/helsinki/"/>
`
etc etc

**Comment by johnclause** [comment]
No that meta is not generated by qtx, but qtx may translate it. Turn off qtx or other plugins in such cases, when you want to find out who is generating what, and see what happens.

**Comment by johnclause** [comment]
What do you mean by "inconsistent use of reflang ("en" vs "fi_FI")"? Anyway, you may control the front-end locales via option "Locale at front-end" on language properties configuration page "/wp-admin/options-general.php?page=qtranslate-x&edit=xx", where "xx" is two-letter code of language to edit, in case you wish to adjust it. Normally it is not necessary, but some people wish to tune it more particularly.

**Comment by johnclause** [comment]
I assume it has been resolved? I am closing it, we can write into closed issue or may reopen it if needed.

**Comment by sailinf** [comment]
Yes
