### ISSUE TITLE
Titles not updated after language switch

### ISSUE THREAD

**Issue by almai** [qTranslate-Team/woocommerce-qtranslate-x#47]
I'm using qtranslate-x with woocommerce and the storefront theme. When I switch languages on the frontpage everything gets displayed in the correct language, except the product titles in the loops. They get displayed in the previous language.

After saving any product and refreshing the frontpage the titles get displayed in the correct language.

![issue](https://user-images.githubusercontent.com/402692/29965189-fbc59056-8f0c-11e7-9170-17ce79e1d3cd.gif)

What can I do to get the titles displayed in the correct language immediatly after switching the language?

**Comment by almai** [comment]
Anybody here, who could give me a hint?

**Comment by ginsterbusch** [comment]
Have you already tested yet, if this issue goes away after being logged out?

cu, w0lf.

**Comment by almai** [comment]
I tried it but logging out has no effect. The error continues.

**Comment by almai** [comment]
There are other places, where the translation doesn't take place correctly.

E. g. the product description.

![bracelet_double-coated_leather_with_gold_disc_ _ameneh_mirzaei](https://user-images.githubusercontent.com/402692/30019055-8e83e98e-915f-11e7-90a4-41c1fe2c27d9.jpg)

Or the tags

![bracelet_double-coated_leather_with_gold_disc_ _ameneh_mirzaei](https://user-images.githubusercontent.com/402692/30019104-b101ac26-915f-11e7-850d-a4015106598f.jpg)

I tried it with different themes (twenty seventeen, twenty sixteen)  in order to exclude the storefront theme from being the origin of the error.

**Comment by almai** [comment]
I had some other places, where the translation didn't work correctly but I was able to fix it. But the problem on the frontpage still continues. Any other suggestions?
