### ISSUE TITLE
how to add not translated terms

### ISSUE THREAD

**Issue by sombodi** [qTranslate-Team/woocommerce-qtranslate-x#6]
Hello helpfull people, 
 I'm sorry if this is a dumb question, but I have searched everywhere and tried everything i can think of. 
The problem is that many woocommerce terms dont have a translated text in qtranslate-x .po files, So I would think that just adding something like this to the qtranslate-es_ES.po file would do it:
# : includes/wc-template-functions.php:1132

msgid "Proceed to Checkout"
msgstr "Continuar a pagar"

But alas, its not working. PLEASE ADVICE! thanks!

**Comment by johnclause** [comment]
Hi, 'woocommerce terms' are supposed to be translated with .po files under Woocommerce. q-X .po files translate its own plugin configuration pages only. Open Woocommerce language folder with .po files, they have instructions on how to update their .po files. Does this answer your question? Reading WP documentation on how translation works in general may help you to tune your question more specifically and to address it in a right place.
